ALTER TABLE elements ADD COLUMN IF NOT EXISTS "props" JSONB;
ALTER TABLE steps ADD COLUMN IF NOT EXISTS "defaultOpen" BOOLEAN;
ALTER TABLE steps ADD COLUMN IF NOT EXISTS "autoCollapse" BOOLEAN;
ALTER TABLE threads ALTER COLUMN "createdAt" DROP NOT NULL;
ALTER TABLE threads ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP::text;
UPDATE threads SET "createdAt" = CURRENT_TIMESTAMP::text WHERE "createdAt" IS NULL;

ALTER TABLE steps ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP::text;
UPDATE steps SET "createdAt" = CURRENT_TIMESTAMP::text WHERE "createdAt" IS NULL;
