ALTER TABLE threads ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP::text;
UPDATE threads SET "createdAt" = CURRENT_TIMESTAMP::text WHERE "createdAt" IS NULL;

ALTER TABLE steps ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP::text;
UPDATE steps SET "createdAt" = CURRENT_TIMESTAMP::text WHERE "createdAt" IS NULL;
